# Generated by Django 5.2.5 on 2025-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('credentials', 'Credentials'), ('google', 'Google'), ('linkedin', 'LinkedIn')], default='credentials', max_length=32),
        ),
    ]
