# Generated by Django 5.2.5 on 2025-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersocialprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usersocialprofile',
            name='provider',
            field=models.CharField(choices=[('credentials', 'Credentials'), ('google', 'Google'), ('linkedin', 'LinkedIn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usersocialprofile',
            name='provider_id',
            field=models.CharField(),
        ),
        migrations.AddConstraint(
            model_name='usersocialprofile',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_id'), name='unique_provider_profile'),
        ),
    ]
